# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20181106_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='finance.Transaction'),
        ),
    ]
