# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20181106_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(default='tmp', max_length=100),
            preserve_default=False,
        ),
    ]
