# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20181106_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorykeyword',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='finance.Category'),
        ),
    ]
