# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20190430_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
