# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20190430_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
