# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-11 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20190430_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='sync_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
