# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20191211_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('accuracy', models.IntegerField()),
                ('text_clf', picklefield.fields.PickledObjectField(editable=False)),
                ('label_encoder', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
